using TMPro;
using Unity.VisualScripting;
using UnityEngine;
using UnityEngine.SceneManagement;
using UnityEngine.UIElements;

public class MenueScript : MonoBehaviour
{
    public void ReturnHome()
    {
        SceneManager.LoadSceneAsync(0);
    }
    public void GameStart()
    {
        SceneManager.LoadSceneAsync(5);
    }

    public void Credits()
    {
        SceneManager.LoadSceneAsync(2);
    }

    public void Shop()
    {
        SceneManager.LoadSceneAsync(1);
    }

    public void Quit()
    {
        Application.Quit();
    }
}

//SceneNummern:
//0 -   MainMenue
//1 -   Shop
//2 -   Credits
//3 -   Lilia
//4 -   Xilver
//5 -   Day1
//6 -   Day6
